### PR TITLE
Add ability to set in options row & column shift and some getters

### PR DESCRIPTION
**Pull request by sgavka**

### CODE REVIEW

**Comment by sgavka** [comment]
https://github.com/itmammoth/Tamotsu_Test/pull/2 and tests for this

**Comment by sgavka** [comment]
JS is not my main language, so I do not know if I make all correct.

**Comment by sgavka** [comment]
And, maybe, I need to write some documentation. I will be make it in next few days.

**Comment by sgavka** [comment]
@itmammoth I added some documentation, so it pull request can be merged.

**Comment by itmammoth** [comment]
Thanks, @sgavka !

I replaced `getXXXCoordinate` methods you added with `baseRange` & `lastRange`.
I think it is better to return a `Range` object as a library because `Range` has some useful methods.

Now you can get row and column via the range, like below.

```javascript
ATable.baseRange().getRow();
ATable.baseRange().getColumn();
ATable.lastRange().getRow();
ATable.lastRange().getColumn();
```

**Pull request merged**
